<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ldg</string>
		<string>ledger</string>
		<string>ldgr</string>
	</array>
	<key>name</key>
	<string>Ledger</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(;.*)$</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.other.date</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.other.edate</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>markup.italic.desc</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(\d{4}[/-]\d{2}[/-]\d{2})([=]?)(\d{4}[/-]\d{2}[/-]\d{2})?\s+(.+)$</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.bold.account</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.other.amount</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s+([\w:\s_-]+)\s+([-$£¥€¢\d.,_]+.*)$</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s+([\w:\s_-]+)\s*$</string>
			<key>name</key>
			<string>markup.bold.account</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.other</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(!\w+)(.*)$</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.other</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^([YPNDCiobh]).*$</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.period</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.other.expression</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(~)\s(.*?)$</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.automated</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.regexp.expression</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(=)\s(.*?)$</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.ledger</string>
	<key>uuid</key>
	<string>806052d8-c579-43e0-918e-02ba9033b149</string>
</dict>
</plist>
